package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblbarrio generated by hbm2java
 */
@Entity
@Table(name="tblbarrio"
    ,catalog="tienda"
)
public class Tblbarrio  implements java.io.Serializable {


     private Integer secbarrio;
     private Tblmunicipio tblmunicipio;
     private String nombre;

    public Tblbarrio() {
    }

    public Tblbarrio(Tblmunicipio tblmunicipio, String nombre) {
       this.tblmunicipio = tblmunicipio;
       this.nombre = nombre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECBARRIO", unique=true, nullable=false)
    public Integer getSecbarrio() {
        return this.secbarrio;
    }
    
    public void setSecbarrio(Integer secbarrio) {
        this.secbarrio = secbarrio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECMUNICIPIO", nullable=false)
    public Tblmunicipio getTblmunicipio() {
        return this.tblmunicipio;
    }
    
    public void setTblmunicipio(Tblmunicipio tblmunicipio) {
        this.tblmunicipio = tblmunicipio;
    }
    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


