package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblcompra generated by hbm2java
 */
@Entity
@Table(name="tblcompra"
    ,catalog="tienda"
)
public class Tblcompra  implements java.io.Serializable {


     private Integer seccompra;
     private Tblpersona tblpersona;
     private Tblproveedor tblproveedor;
     private Tblpuntodeventa tblpuntodeventa;
     private BigDecimal total;
     private BigDecimal totalCantidad;
     private String descripcion;
     private Set tbldetallecompras = new HashSet(0);

    public Tblcompra() {
    }

	
    public Tblcompra(Tblpersona tblpersona, Tblproveedor tblproveedor, Tblpuntodeventa tblpuntodeventa, BigDecimal total, BigDecimal totalCantidad, String descripcion) {
        this.tblpersona = tblpersona;
        this.tblproveedor = tblproveedor;
        this.tblpuntodeventa = tblpuntodeventa;
        this.total = total;
        this.totalCantidad = totalCantidad;
        this.descripcion = descripcion;
    }
    public Tblcompra(Tblpersona tblpersona, Tblproveedor tblproveedor, Tblpuntodeventa tblpuntodeventa, BigDecimal total, BigDecimal totalCantidad, String descripcion, Set tbldetallecompras) {
       this.tblpersona = tblpersona;
       this.tblproveedor = tblproveedor;
       this.tblpuntodeventa = tblpuntodeventa;
       this.total = total;
       this.totalCantidad = totalCantidad;
       this.descripcion = descripcion;
       this.tbldetallecompras = tbldetallecompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECCOMPRA", unique=true, nullable=false)
    public Integer getSeccompra() {
        return this.seccompra;
    }
    
    public void setSeccompra(Integer seccompra) {
        this.seccompra = seccompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPERSONA", nullable=false)
    public Tblpersona getTblpersona() {
        return this.tblpersona;
    }
    
    public void setTblpersona(Tblpersona tblpersona) {
        this.tblpersona = tblpersona;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPROVEEDOR", nullable=false)
    public Tblproveedor getTblproveedor() {
        return this.tblproveedor;
    }
    
    public void setTblproveedor(Tblproveedor tblproveedor) {
        this.tblproveedor = tblproveedor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPUNTODEVENTA", nullable=false)
    public Tblpuntodeventa getTblpuntodeventa() {
        return this.tblpuntodeventa;
    }
    
    public void setTblpuntodeventa(Tblpuntodeventa tblpuntodeventa) {
        this.tblpuntodeventa = tblpuntodeventa;
    }
    
    @Column(name="TOTAL", nullable=false, precision=50, scale=0)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    
    @Column(name="TOTAL_CANTIDAD", nullable=false, precision=50, scale=0)
    public BigDecimal getTotalCantidad() {
        return this.totalCantidad;
    }
    
    public void setTotalCantidad(BigDecimal totalCantidad) {
        this.totalCantidad = totalCantidad;
    }
    
    @Column(name="DESCRIPCION", nullable=false, length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblcompra")
    public Set getTbldetallecompras() {
        return this.tbldetallecompras;
    }
    
    public void setTbldetallecompras(Set tbldetallecompras) {
        this.tbldetallecompras = tbldetallecompras;
    }




}


