package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblcategoria generated by hbm2java
 */
@Entity
@Table(name="tblcategoria"
    ,catalog="tienda"
)
public class Tblcategoria  implements java.io.Serializable {


     private Integer seccategoria;
     private String nombrecategoria;
     private Set tblproductos = new HashSet(0);

    public Tblcategoria() {
    }

	
    public Tblcategoria(String nombrecategoria) {
        this.nombrecategoria = nombrecategoria;
    }
    public Tblcategoria(String nombrecategoria, Set tblproductos) {
       this.nombrecategoria = nombrecategoria;
       this.tblproductos = tblproductos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECCATEGORIA", unique=true, nullable=false)
    public Integer getSeccategoria() {
        return this.seccategoria;
    }
    
    public void setSeccategoria(Integer seccategoria) {
        this.seccategoria = seccategoria;
    }
    
    @Column(name="NOMBRECATEGORIA", nullable=false, length=45)
    public String getNombrecategoria() {
        return this.nombrecategoria;
    }
    
    public void setNombrecategoria(String nombrecategoria) {
        this.nombrecategoria = nombrecategoria;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblcategoria")
    public Set getTblproductos() {
        return this.tblproductos;
    }
    
    public void setTblproductos(Set tblproductos) {
        this.tblproductos = tblproductos;
    }




}


