package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbldepartamento generated by hbm2java
 */
@Entity
@Table(name="tbldepartamento"
    ,catalog="tienda"
)
public class Tbldepartamento  implements java.io.Serializable {


     private Integer secdepartamento;
     private Tblpais tblpais;
     private String nombre;
     private Set tblmunicipios = new HashSet(0);

    public Tbldepartamento() {
    }

	
    public Tbldepartamento(Tblpais tblpais, String nombre) {
        this.tblpais = tblpais;
        this.nombre = nombre;
    }
    public Tbldepartamento(Tblpais tblpais, String nombre, Set tblmunicipios) {
       this.tblpais = tblpais;
       this.nombre = nombre;
       this.tblmunicipios = tblmunicipios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECDEPARTAMENTO", unique=true, nullable=false)
    public Integer getSecdepartamento() {
        return this.secdepartamento;
    }
    
    public void setSecdepartamento(Integer secdepartamento) {
        this.secdepartamento = secdepartamento;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPAIS", nullable=false)
    public Tblpais getTblpais() {
        return this.tblpais;
    }
    
    public void setTblpais(Tblpais tblpais) {
        this.tblpais = tblpais;
    }
    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbldepartamento")
    public Set getTblmunicipios() {
        return this.tblmunicipios;
    }
    
    public void setTblmunicipios(Set tblmunicipios) {
        this.tblmunicipios = tblmunicipios;
    }




}


