package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tbldetallecompra generated by hbm2java
 */
@Entity
@Table(name="tbldetallecompra"
    ,catalog="tienda"
)
public class Tbldetallecompra  implements java.io.Serializable {


     private Integer secdetallecompra;
     private Tblcompra tblcompra;
     private Tblproducto tblproducto;
     private int cantidad;
     private BigDecimal subtotal;

    public Tbldetallecompra() {
    }

    public Tbldetallecompra(Tblcompra tblcompra, Tblproducto tblproducto, int cantidad, BigDecimal subtotal) {
       this.tblcompra = tblcompra;
       this.tblproducto = tblproducto;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECDETALLECOMPRA", unique=true, nullable=false)
    public Integer getSecdetallecompra() {
        return this.secdetallecompra;
    }
    
    public void setSecdetallecompra(Integer secdetallecompra) {
        this.secdetallecompra = secdetallecompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECCOMPRA", nullable=false)
    public Tblcompra getTblcompra() {
        return this.tblcompra;
    }
    
    public void setTblcompra(Tblcompra tblcompra) {
        this.tblcompra = tblcompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPRODUCTO", nullable=false)
    public Tblproducto getTblproducto() {
        return this.tblproducto;
    }
    
    public void setTblproducto(Tblproducto tblproducto) {
        this.tblproducto = tblproducto;
    }
    
    @Column(name="CANTIDAD", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="SUBTOTAL", nullable=false, precision=50, scale=0)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }




}


