package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbldocumento generated by hbm2java
 */
@Entity
@Table(name="tbldocumento"
    ,catalog="tienda"
)
public class Tbldocumento  implements java.io.Serializable {


     private Integer secdocumento;
     private Tbltipodocumento tbltipodocumento;
     private String numero;
     private Set tblpersonas = new HashSet(0);

    public Tbldocumento() {
    }

	
    public Tbldocumento(Tbltipodocumento tbltipodocumento, String numero) {
        this.tbltipodocumento = tbltipodocumento;
        this.numero = numero;
    }
    public Tbldocumento(Tbltipodocumento tbltipodocumento, String numero, Set tblpersonas) {
       this.tbltipodocumento = tbltipodocumento;
       this.numero = numero;
       this.tblpersonas = tblpersonas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECDOCUMENTO", unique=true, nullable=false)
    public Integer getSecdocumento() {
        return this.secdocumento;
    }
    
    public void setSecdocumento(Integer secdocumento) {
        this.secdocumento = secdocumento;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECTIPODOCUMENTO", nullable=false)
    public Tbltipodocumento getTbltipodocumento() {
        return this.tbltipodocumento;
    }
    
    public void setTbltipodocumento(Tbltipodocumento tbltipodocumento) {
        this.tbltipodocumento = tbltipodocumento;
    }
    
    @Column(name="NUMERO", nullable=false, length=45)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbldocumento")
    public Set getTblpersonas() {
        return this.tblpersonas;
    }
    
    public void setTblpersonas(Set tblpersonas) {
        this.tblpersonas = tblpersonas;
    }




}


