package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblmunicipio generated by hbm2java
 */
@Entity
@Table(name="tblmunicipio"
    ,catalog="tienda"
)
public class Tblmunicipio  implements java.io.Serializable {


     private Integer secmunicipio;
     private Tbldepartamento tbldepartamento;
     private String nombre;
     private Set tblbarrios = new HashSet(0);
     private Set tblpersonas = new HashSet(0);
     private Set tblproveedors = new HashSet(0);

    public Tblmunicipio() {
    }

	
    public Tblmunicipio(Tbldepartamento tbldepartamento, String nombre) {
        this.tbldepartamento = tbldepartamento;
        this.nombre = nombre;
    }
    public Tblmunicipio(Tbldepartamento tbldepartamento, String nombre, Set tblbarrios, Set tblpersonas, Set tblproveedors) {
       this.tbldepartamento = tbldepartamento;
       this.nombre = nombre;
       this.tblbarrios = tblbarrios;
       this.tblpersonas = tblpersonas;
       this.tblproveedors = tblproveedors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECMUNICIPIO", unique=true, nullable=false)
    public Integer getSecmunicipio() {
        return this.secmunicipio;
    }
    
    public void setSecmunicipio(Integer secmunicipio) {
        this.secmunicipio = secmunicipio;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECDEPARTAMENTO", nullable=false)
    public Tbldepartamento getTbldepartamento() {
        return this.tbldepartamento;
    }
    
    public void setTbldepartamento(Tbldepartamento tbldepartamento) {
        this.tbldepartamento = tbldepartamento;
    }
    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblmunicipio")
    public Set getTblbarrios() {
        return this.tblbarrios;
    }
    
    public void setTblbarrios(Set tblbarrios) {
        this.tblbarrios = tblbarrios;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblmunicipio")
    public Set getTblpersonas() {
        return this.tblpersonas;
    }
    
    public void setTblpersonas(Set tblpersonas) {
        this.tblpersonas = tblpersonas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblmunicipio")
    public Set getTblproveedors() {
        return this.tblproveedors;
    }
    
    public void setTblproveedors(Set tblproveedors) {
        this.tblproveedors = tblproveedors;
    }




}


