package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblpuntodeventa generated by hbm2java
 */
@Entity
@Table(name="tblpuntodeventa"
    ,catalog="tienda"
)
public class Tblpuntodeventa  implements java.io.Serializable {


     private Integer secpuntodeventa;
     private Tblpersona tblpersona;
     private String nombre;
     private String direccion;
     private String email;
     private String telefono;
     private String nit;
     private Set tblventas = new HashSet(0);
     private Set tblcompras = new HashSet(0);

    public Tblpuntodeventa() {
    }

	
    public Tblpuntodeventa(Tblpersona tblpersona, String nombre, String direccion, String email, String telefono, String nit) {
        this.tblpersona = tblpersona;
        this.nombre = nombre;
        this.direccion = direccion;
        this.email = email;
        this.telefono = telefono;
        this.nit = nit;
    }
    public Tblpuntodeventa(Tblpersona tblpersona, String nombre, String direccion, String email, String telefono, String nit, Set tblventas, Set tblcompras) {
       this.tblpersona = tblpersona;
       this.nombre = nombre;
       this.direccion = direccion;
       this.email = email;
       this.telefono = telefono;
       this.nit = nit;
       this.tblventas = tblventas;
       this.tblcompras = tblcompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECPUNTODEVENTA", unique=true, nullable=false)
    public Integer getSecpuntodeventa() {
        return this.secpuntodeventa;
    }
    
    public void setSecpuntodeventa(Integer secpuntodeventa) {
        this.secpuntodeventa = secpuntodeventa;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPERSONA", nullable=false)
    public Tblpersona getTblpersona() {
        return this.tblpersona;
    }
    
    public void setTblpersona(Tblpersona tblpersona) {
        this.tblpersona = tblpersona;
    }
    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="DIRECCION", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="EMAIL", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="TELEFONO", nullable=false, length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="NIT", nullable=false, length=45)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblpuntodeventa")
    public Set getTblventas() {
        return this.tblventas;
    }
    
    public void setTblventas(Set tblventas) {
        this.tblventas = tblventas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblpuntodeventa")
    public Set getTblcompras() {
        return this.tblcompras;
    }
    
    public void setTblcompras(Set tblcompras) {
        this.tblcompras = tblcompras;
    }




}


