package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblproveedor generated by hbm2java
 */
@Entity
@Table(name="tblproveedor"
    ,catalog="tienda"
)
public class Tblproveedor  implements java.io.Serializable {


     private Integer secproveedor;
     private Tblmunicipio tblmunicipio;
     private String nombre;
     private String telefono;
     private String direccion;
     private String email;
     private String nit;
     private Set tblproductos = new HashSet(0);
     private Set tblcompras = new HashSet(0);

    public Tblproveedor() {
    }

	
    public Tblproveedor(Tblmunicipio tblmunicipio, String nombre, String telefono, String direccion, String email, String nit) {
        this.tblmunicipio = tblmunicipio;
        this.nombre = nombre;
        this.telefono = telefono;
        this.direccion = direccion;
        this.email = email;
        this.nit = nit;
    }
    public Tblproveedor(Tblmunicipio tblmunicipio, String nombre, String telefono, String direccion, String email, String nit, Set tblproductos, Set tblcompras) {
       this.tblmunicipio = tblmunicipio;
       this.nombre = nombre;
       this.telefono = telefono;
       this.direccion = direccion;
       this.email = email;
       this.nit = nit;
       this.tblproductos = tblproductos;
       this.tblcompras = tblcompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECPROVEEDOR", unique=true, nullable=false)
    public Integer getSecproveedor() {
        return this.secproveedor;
    }
    
    public void setSecproveedor(Integer secproveedor) {
        this.secproveedor = secproveedor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECMUNICIPIO", nullable=false)
    public Tblmunicipio getTblmunicipio() {
        return this.tblmunicipio;
    }
    
    public void setTblmunicipio(Tblmunicipio tblmunicipio) {
        this.tblmunicipio = tblmunicipio;
    }
    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="TELEFONO", nullable=false, length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="DIRECCION", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="EMAIL", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="NIT", nullable=false, length=45)
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblproveedor")
    public Set getTblproductos() {
        return this.tblproductos;
    }
    
    public void setTblproductos(Set tblproductos) {
        this.tblproductos = tblproductos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblproveedor")
    public Set getTblcompras() {
        return this.tblcompras;
    }
    
    public void setTblcompras(Set tblcompras) {
        this.tblcompras = tblcompras;
    }




}


