package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tblpreciocompra generated by hbm2java
 */
@Entity
@Table(name="tblpreciocompra"
    ,catalog="tienda"
)
public class Tblpreciocompra  implements java.io.Serializable {


     private Integer secprecioCompra;
     private Date fecha;
     private BigDecimal precio;
     private Set tblproductos = new HashSet(0);

    public Tblpreciocompra() {
    }

	
    public Tblpreciocompra(Date fecha, BigDecimal precio) {
        this.fecha = fecha;
        this.precio = precio;
    }
    public Tblpreciocompra(Date fecha, BigDecimal precio, Set tblproductos) {
       this.fecha = fecha;
       this.precio = precio;
       this.tblproductos = tblproductos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECPRECIO_COMPRA", unique=true, nullable=false)
    public Integer getSecprecioCompra() {
        return this.secprecioCompra;
    }
    
    public void setSecprecioCompra(Integer secprecioCompra) {
        this.secprecioCompra = secprecioCompra;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="PRECIO", nullable=false, precision=50, scale=0)
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblpreciocompra")
    public Set getTblproductos() {
        return this.tblproductos;
    }
    
    public void setTblproductos(Set tblproductos) {
        this.tblproductos = tblproductos;
    }




}


