package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblproducto generated by hbm2java
 */
@Entity
@Table(name="tblproducto"
    ,catalog="tienda"
)
public class Tblproducto  implements java.io.Serializable {


     private Integer secproducto;
     private Tblpreciocompra tblpreciocompra;
     private Tblcategoria tblcategoria;
     private Tblmarca tblmarca;
     private Tblproveedor tblproveedor;
     private Tblunidad tblunidad;
     private String nombreProducto;
     private int codigo;
     private int cantidad;
     private BigDecimal precioventa;
     private Set tbldetalleventas = new HashSet(0);
     private Set tbldetallecompras = new HashSet(0);

    public Tblproducto() {
    }

	
    public Tblproducto(Tblpreciocompra tblpreciocompra, Tblcategoria tblcategoria, Tblmarca tblmarca, Tblproveedor tblproveedor, Tblunidad tblunidad, String nombreProducto, int codigo, int cantidad, BigDecimal precioventa) {
        this.tblpreciocompra = tblpreciocompra;
        this.tblcategoria = tblcategoria;
        this.tblmarca = tblmarca;
        this.tblproveedor = tblproveedor;
        this.tblunidad = tblunidad;
        this.nombreProducto = nombreProducto;
        this.codigo = codigo;
        this.cantidad = cantidad;
        this.precioventa = precioventa;
    }
    public Tblproducto(Tblpreciocompra tblpreciocompra, Tblcategoria tblcategoria, Tblmarca tblmarca, Tblproveedor tblproveedor, Tblunidad tblunidad, String nombreProducto, int codigo, int cantidad, BigDecimal precioventa, Set tbldetalleventas, Set tbldetallecompras) {
       this.tblpreciocompra = tblpreciocompra;
       this.tblcategoria = tblcategoria;
       this.tblmarca = tblmarca;
       this.tblproveedor = tblproveedor;
       this.tblunidad = tblunidad;
       this.nombreProducto = nombreProducto;
       this.codigo = codigo;
       this.cantidad = cantidad;
       this.precioventa = precioventa;
       this.tbldetalleventas = tbldetalleventas;
       this.tbldetallecompras = tbldetallecompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECPRODUCTO", unique=true, nullable=false)
    public Integer getSecproducto() {
        return this.secproducto;
    }
    
    public void setSecproducto(Integer secproducto) {
        this.secproducto = secproducto;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPRECIOCOMPRA", nullable=false)
    public Tblpreciocompra getTblpreciocompra() {
        return this.tblpreciocompra;
    }
    
    public void setTblpreciocompra(Tblpreciocompra tblpreciocompra) {
        this.tblpreciocompra = tblpreciocompra;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECCATEGORIA", nullable=false)
    public Tblcategoria getTblcategoria() {
        return this.tblcategoria;
    }
    
    public void setTblcategoria(Tblcategoria tblcategoria) {
        this.tblcategoria = tblcategoria;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECMARCA", nullable=false)
    public Tblmarca getTblmarca() {
        return this.tblmarca;
    }
    
    public void setTblmarca(Tblmarca tblmarca) {
        this.tblmarca = tblmarca;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECPROVEEDOR", nullable=false)
    public Tblproveedor getTblproveedor() {
        return this.tblproveedor;
    }
    
    public void setTblproveedor(Tblproveedor tblproveedor) {
        this.tblproveedor = tblproveedor;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECUNIDAD", nullable=false)
    public Tblunidad getTblunidad() {
        return this.tblunidad;
    }
    
    public void setTblunidad(Tblunidad tblunidad) {
        this.tblunidad = tblunidad;
    }
    
    @Column(name="NOMBRE_PRODUCTO", nullable=false, length=45)
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    
    @Column(name="CODIGO", nullable=false)
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="CANTIDAD", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    
    @Column(name="PRECIOVENTA", nullable=false, precision=50, scale=0)
    public BigDecimal getPrecioventa() {
        return this.precioventa;
    }
    
    public void setPrecioventa(BigDecimal precioventa) {
        this.precioventa = precioventa;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblproducto")
    public Set getTbldetalleventas() {
        return this.tbldetalleventas;
    }
    
    public void setTbldetalleventas(Set tbldetalleventas) {
        this.tbldetalleventas = tbldetalleventas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblproducto")
    public Set getTbldetallecompras() {
        return this.tbldetallecompras;
    }
    
    public void setTbldetallecompras(Set tbldetallecompras) {
        this.tbldetallecompras = tbldetallecompras;
    }




}


