package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblrol generated by hbm2java
 */
@Entity
@Table(name="tblrol"
    ,catalog="tienda"
)
public class Tblrol  implements java.io.Serializable {


     private Integer secrol;
     private String descripcion;
     private Set tblusuarios = new HashSet(0);

    public Tblrol() {
    }

	
    public Tblrol(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tblrol(String descripcion, Set tblusuarios) {
       this.descripcion = descripcion;
       this.tblusuarios = tblusuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECROL", unique=true, nullable=false)
    public Integer getSecrol() {
        return this.secrol;
    }
    
    public void setSecrol(Integer secrol) {
        this.secrol = secrol;
    }
    
    @Column(name="DESCRIPCION", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblrol")
    public Set getTblusuarios() {
        return this.tblusuarios;
    }
    
    public void setTblusuarios(Set tblusuarios) {
        this.tblusuarios = tblusuarios;
    }




}


