package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tblsexo generated by hbm2java
 */
@Entity
@Table(name="tblsexo"
    ,catalog="tienda"
)
public class Tblsexo  implements java.io.Serializable {


     private Integer secsexo;
     private String descripcion;
     private Set tblpersonas = new HashSet(0);

    public Tblsexo() {
    }

	
    public Tblsexo(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tblsexo(String descripcion, Set tblpersonas) {
       this.descripcion = descripcion;
       this.tblpersonas = tblpersonas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECSEXO", unique=true, nullable=false)
    public Integer getSecsexo() {
        return this.secsexo;
    }
    
    public void setSecsexo(Integer secsexo) {
        this.secsexo = secsexo;
    }
    
    @Column(name="DESCRIPCION", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tblsexo")
    public Set getTblpersonas() {
        return this.tblpersonas;
    }
    
    public void setTblpersonas(Set tblpersonas) {
        this.tblpersonas = tblpersonas;
    }




}


