package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tbltipodocumento generated by hbm2java
 */
@Entity
@Table(name="tbltipodocumento"
    ,catalog="tienda"
)
public class Tbltipodocumento  implements java.io.Serializable {


     private Integer sectipodocumento;
     private String descripcion;
     private Set tbldocumentos = new HashSet(0);

    public Tbltipodocumento() {
    }

	
    public Tbltipodocumento(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tbltipodocumento(String descripcion, Set tbldocumentos) {
       this.descripcion = descripcion;
       this.tbldocumentos = tbldocumentos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECTIPODOCUMENTO", unique=true, nullable=false)
    public Integer getSectipodocumento() {
        return this.sectipodocumento;
    }
    
    public void setSectipodocumento(Integer sectipodocumento) {
        this.sectipodocumento = sectipodocumento;
    }
    
    @Column(name="DESCRIPCION", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tbltipodocumento")
    public Set getTbldocumentos() {
        return this.tbldocumentos;
    }
    
    public void setTbldocumentos(Set tbldocumentos) {
        this.tbldocumentos = tbldocumentos;
    }




}


