package com.triunfo.entidades;
// Generated 24/08/2013 06:40:00 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tblusuario generated by hbm2java
 */
@Entity
@Table(name="tblusuario"
    ,catalog="tienda"
)
public class Tblusuario  implements java.io.Serializable {


     private Integer secusuario;
     private Tblrol tblrol;
     private String login;
     private String password;

    public Tblusuario() {
    }

    public Tblusuario(Tblrol tblrol, String login, String password) {
       this.tblrol = tblrol;
       this.login = login;
       this.password = password;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="SECUSUARIO", unique=true, nullable=false)
    public Integer getSecusuario() {
        return this.secusuario;
    }
    
    public void setSecusuario(Integer secusuario) {
        this.secusuario = secusuario;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SECROL", nullable=false)
    public Tblrol getTblrol() {
        return this.tblrol;
    }
    
    public void setTblrol(Tblrol tblrol) {
        this.tblrol = tblrol;
    }
    
    @Column(name="LOGIN", nullable=false, length=45)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name="PASSWORD", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


